import { ArrowRight, BarChart3, Github, ScanSearch, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";

import { Button, Card } from "@/components/ui";
import { authUrl } from "@/lib/api";

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-slate-950 text-white"><div className="pointer-events-none absolute inset-x-0 top-0 h-[520px] bg-[radial-gradient(circle_at_50%_0%,rgba(34,211,238,.18),transparent_60%)]" /><nav className="relative mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 font-bold"><span className="grid size-9 place-items-center rounded-xl bg-cyan-300 text-slate-950"><ScanSearch size={19} /></span>BugRisk AI</Link><Link className="text-sm text-slate-400 hover:text-white" href="/models">Model card</Link></nav><section className="relative mx-auto max-w-5xl px-5 pb-24 pt-20 text-center sm:pt-28"><div className="mx-auto inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/[0.07] px-3 py-1 text-xs font-semibold text-cyan-200"><Sparkles size={13} />Explainable engineering risk</div><h1 className="mx-auto mt-7 max-w-4xl text-5xl font-black leading-[1.02] tracking-[-.045em] sm:text-7xl">Know where the next bug is <span className="bg-gradient-to-r from-cyan-300 to-emerald-300 bg-clip-text text-transparent">most likely to hide.</span></h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-slate-400">BugRisk AI analyzes Git history, code churn, and complexity to prioritize review—then explains every signal behind the score.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild className="h-12 px-6"><a href={authUrl}><Github className="mr-2" size={18} />Continue with GitHub</a></Button><Button asChild variant="secondary" className="h-12 px-6"><Link href="/dashboard">Explore demo <ArrowRight className="ml-2" size={18} /></Link></Button></div><p className="mt-4 text-xs text-slate-600">Risk prioritizes human review. It never replaces it.</p></section><section className="relative mx-auto grid max-w-6xl gap-4 px-5 pb-24 md:grid-cols-3"><Feature icon={<BarChart3 />} title="Change-risk prediction" text="A calibrated model estimates whether the analyzed commit deserves deeper review." /><Feature icon={<ScanSearch />} title="File prioritization" text="Transparent ranking combines change risk with churn, history, and complexity." /><Feature icon={<ShieldCheck />} title="Actionable evidence" text="SHAP contributions become focused review and testing recommendations." /></section></main>;
}

function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <Card className="p-6"><span className="grid size-10 place-items-center rounded-xl bg-cyan-300/10 text-cyan-300">{icon}</span><h2 className="mt-5 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></Card>; }

