import base64
import hashlib
import hmac
import json
import time
from typing import Any

import httpx
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from fastapi import HTTPException

from .config import Settings

GITHUB_API = "https://api.github.com"
GITHUB_HEADERS = {"Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28"}


def verify_webhook_signature(body: bytes, signature: str | None, secret: str | None) -> bool:
    if not signature or not secret or not signature.startswith("sha256="):
        return False
    expected = "sha256=" + hmac.new(secret.encode(), body, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, signature)


def _b64url(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).rstrip(b"=").decode()


def app_jwt(settings: Settings) -> str:
    private_key = settings.normalized_github_app_private_key
    if not settings.github_app_id or not private_key:
        raise HTTPException(503, "GitHub App authentication is not configured")
    now = int(time.time())
    header = _b64url(json.dumps({"alg": "RS256", "typ": "JWT"}, separators=(",", ":")).encode())
    payload = _b64url(
        json.dumps(
            {"iat": now - 60, "exp": now + 540, "iss": settings.github_app_id},
            separators=(",", ":"),
        ).encode()
    )
    signing_input = f"{header}.{payload}".encode()
    key = serialization.load_pem_private_key(private_key.encode(), password=None)
    if not isinstance(key, rsa.RSAPrivateKey):
        raise ValueError("GitHub App private key must be an RSA key")
    signature = key.sign(signing_input, padding.PKCS1v15(), hashes.SHA256())
    return f"{header}.{payload}.{_b64url(signature)}"


async def installation_token(settings: Settings, installation_id: str) -> str:
    async with httpx.AsyncClient(timeout=20) as client:
        response = await client.post(
            f"{GITHUB_API}/app/installations/{installation_id}/access_tokens",
            headers={**GITHUB_HEADERS, "Authorization": f"Bearer {app_jwt(settings)}"},
        )
        response.raise_for_status()
        return str(response.json()["token"])


async def pull_request_files(owner: str, repository: str, number: int, token: str) -> list[str]:
    paths: list[str] = []
    async with httpx.AsyncClient(timeout=20) as client:
        page = 1
        while True:
            response = await client.get(
                f"{GITHUB_API}/repos/{owner}/{repository}/pulls/{number}/files",
                params={"per_page": 100, "page": page},
                headers={**GITHUB_HEADERS, "Authorization": f"Bearer {token}"},
            )
            response.raise_for_status()
            items = response.json()
            paths.extend(str(item["filename"]) for item in items)
            if len(items) < 100:
                return paths
            page += 1


def render_pull_request_report(pull_request: Any, analysis: Any, files: list[Any]) -> str:
    risk = round(float(analysis.change_risk_probability or 0) * 100)
    ranked = sorted(files, key=lambda item: item.file_priority_score, reverse=True)[:10]
    rows = "\n".join(
        f"| `{item.file_path}` | {round(item.file_priority_score * 100)}% "
        f"| {item.risk_level.value} |"
        for item in ranked
    )
    if not rows:
        rows = "| No changed Python files were analyzed | - | - |"
    factors: list[str] = []
    if ranked:
        strongest = sorted(
            ranked[0].explanations,
            key=lambda item: abs(item["shap_value"]),
            reverse=True,
        )[:3]
        for factor in strongest:
            feature = factor["feature_name"].replace("_", " ").title()
            factors.append(f"- **{feature}**: SHAP {factor['shap_value']:+.3f}")
    recommendations = "\n".join(
        f"- {item}" for item in (ranked[0].recommendations[:3] if ranked else [])
    )
    return (
        "## BugRisk AI change-risk report\n\n"
        f"**Calibrated change risk:** {risk}% ({analysis.risk_level.value})  \n"
        f"**Analyzed commit:** `{analysis.commit_sha[:12]}`  \n"
        f"**Changed Python files analyzed:** {len(files)}\n\n"
        "File scores are review-priority rankings, not probabilities that a file "
        "contains a bug.\n\n"
        "| File | Priority | Level |\n| --- | ---: | --- |\n"
        f"{rows}\n\n"
        "### Strongest evidence\n"
        f"{chr(10).join(factors) or '- No model evidence available.'}\n\n"
        "### Recommended checks\n"
        f"{recommendations or '- Complete peer review and focused regression testing.'}\n\n"
        "_Generated by BugRisk AI. Use this report to prioritize review and testing; "
        "it does not guarantee defects._"
    )


async def publish_pull_request_report(
    settings: Settings, pull_request: Any, analysis: Any, files: list[Any]
) -> str:
    token = await installation_token(settings, pull_request.installation_id)
    body = {"body": render_pull_request_report(pull_request, analysis, files)}
    owner = pull_request.repository.owner
    repository = pull_request.repository.name
    if pull_request.github_comment_id:
        url = (
            f"{GITHUB_API}/repos/{owner}/{repository}/issues/comments/"
            f"{pull_request.github_comment_id}"
        )
        method = "patch"
    else:
        url = (
            f"{GITHUB_API}/repos/{owner}/{repository}/issues/"
            f"{pull_request.github_pr_number}/comments"
        )
        method = "post"
    async with httpx.AsyncClient(timeout=20) as client:
        response = await getattr(client, method)(
            url,
            json=body,
            headers={**GITHUB_HEADERS, "Authorization": f"Bearer {token}"},
        )
        response.raise_for_status()
        return str(response.json()["id"])
